############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
  name = "Resumé"
  identifer = "Resumé"
  url = "Tim-Bailey-Jones-Resume-January-2025.pdf"
  weight = 2

[[main]]
  name = "Blog"
  identifer = "Blog"
  url = "/blog"
  weight = 3

[[main]]
  name = "Career"
  identifer = "Career"
  url = "/career"
  weight = 3


 [[main]]
  name = "Links"
  weight = 5

[[main]]
  parent = "Links"
  name = "TimCod.es"
  url = "https://timcod.es/"

[[main]]
  parent = "Links"
  name = "My LinkedIn Profile"
  url = "https://www.linkedin.com/in/timbaileyjones"

[[main]]
  parent = "Links"
  name = "Tampa.Dev"
  url = "https://talent.tampa.dev/developers/VrGnSlPp"

[[main]]
  parent = "Links"
  name = "My Twitter"
  url = "https://twitter.com/timbaileyjones"

[[main]]
  name = "Music"
  identifier = "Music"
  weight = 6
[[main]]
  parent = "Music"
  name = "Tim Jones Music"
  url = "https://timjones.com/"
  weight = 10
[[main]]
  parent = "Music"
  name = "Gaspar Brass Quintet"
  url = "https://gasparbrass.com/"
  weight = 11
[[main]]
  parent = "Music"
  name = "Cypress Creek Dixieland Jazz Band"
  url = "https://CypressCreekDixieland.com/"
  weight = 12

[[main]]
  parent = "Music"
  name = "Wesley Chapel Wind Ensemble"
  url = "https://facebook.com/profile.php?id=100038994229181"
  weight = 13

[[main]]
  parent = "Music"
  name = "Dade City Symphony"
  url = "https://dadecitysymphony.com"
  weight = 14

[[main]]
  parent = "Music"
  name = "Carrollwood Brass Ensemble"
  url = "https://carrollwoodbrass.com"
  weight = 15

[[main]]
  parent = "Music"
  name = "Southshore Symphony Orchestra"
  url = "https://southshoresymphonyorchestra.org"
  weight = 18
  

[[main]]
  parent = "Music"
  name = "Facebook Saved Music Videos (requires login)"
  url = "https://facebook.com/saved/?list_id=10168284416880002"
  weight = 16

# [[main]]
#   name = "About"
#   url = "about/"
#   weight = 8

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/timbaileyjones"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/timbaileyjones"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://linkedin.com/in/timbaileyjones"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"
[[social]]
name = "facebook"
url = "https://facebook.com/timbaileyjones"
# other supported social links

# name = "youtube"
# url = "https://www.youtube.com/#"

# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"


# [[main]]
#   name = "About"
#   url = "/about"
#   weight = 2

#[[main]]
#  name = "Elements"
#  url = "/elements"
#  weight = 4

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "/contact"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "/authors"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "/categories"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
