options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - id: 'Install dependencies'
    name: 'node:lts'
    entrypoint: 'npm'
    args: ['install']

  - id: 'Build site'
    name: 'node:lts'
    entrypoint: 'npm'
    args: ['run', 'build']

  - id: 'Deploy to GCS'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['storage', 'rsync', '_site/', 'gs://bailey-jones.com', '--recursive', '--delete-unmatched-destination-objects']

  - id: 'Invalidate CDN cache'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['compute', 'url-maps', 'invalidate-cdn-cache', 'website-url-map', '--global', '--path=/*']
